### ISSUE TITLE
Display Key Fingerprint during Validation

### ISSUE THREAD

**Issue by Pharb** [TNG/gpg-validation-server#33]
Make sure key fingerprint can be checked by the user during validation:
- include in emails
- show on verification HTML page

**Comment by JohannesEbke** [comment]
I've added it to the mails; and since the Fingerprint is now in the Mail you clicked the verification link on, I don't think showing the fingerprint on the verification page is really helpful.

It also makes it so that the verification page can "leak" information; rather than always showing the accepted page if a well-formed nonce has been passed. I am not sure if this is a problem, but i would like to avoid it if possible.
